### ISSUE TITLE
Why not json encode

### ISSUE THREAD

**Issue by dereuromark** [burzum/cakephp-serialize-data-types#1]
Why using serialize/unserialize when the latter can "execute" stuff, making it potentially dangerous to store things this way.

Using json encode/decode this problem would not exist, the speed should be the same etc.

**Comment by burzum** [comment]
Json is already there. https://github.com/burzum/cakephp-serialize-data-types/blob/master/src/Database/Type/JsonType.php

**I'm** aware of the problems with serialize(), so I leave it up to everyone else to use one of both. I'm not in charge for stupid or insecure code other people write. Feel free to add documentation that explains the problem.

**Comment by dereuromark** [comment]
Lol
Well I leave that up to you then
